spring:
  profiles:
    active: db, core, wx
  messages:
    encoding: UTF-8

server:
  port: 8082

logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  ERROR
    org.joy.litemall.wx:  DEBUG
    org.joy.litemall:  ERROR

swagger:
  production: false